const http=require('http');
const fs=require('fs');
const fsp=fs.promises;
const path=require('path');
const os=require('os');
const ROOT=__dirname, DATA_DIR=path.join(ROOT,'data'), DATA_FILE=path.join(DATA_DIR,'library.json');
const PORT=Number(process.env.PORT||8787);
let queue=Promise.resolve();
const withLock=fn=>{const p=queue.then(fn,fn);queue=p.catch(()=>{});return p};
const todayISO=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const addDaysISO=(days,iso=todayISO())=>{const d=new Date(iso+'T12:00:00');d.setDate(d.getDate()+Number(days||0));return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
async function readState(){try{return JSON.parse(await fsp.readFile(DATA_FILE,'utf8'))}catch(e){if(e.code==='ENOENT')return null;throw e}}
async function writeState(state){await fsp.mkdir(DATA_DIR,{recursive:true});const tmp=DATA_FILE+'.tmp';await fsp.writeFile(tmp,JSON.stringify(state,null,2),'utf8');await fsp.rename(tmp,DATA_FILE)}
function derive(s){if(!s)return s;const today=todayISO();s.loans=Array.isArray(s.loans)?s.loans:[];s.books=Array.isArray(s.books)?s.books:[];s.students=Array.isArray(s.students)?s.students:[];s.reservations=Array.isArray(s.reservations)?s.reservations:[];s.activityLogs=Array.isArray(s.activityLogs)?s.activityLogs:[];s.config=s.config||{};s.stations=Array.isArray(s.stations)?s.stations:[];s.meta=s.meta||{revision:0};for(const l of s.loans){if(l.status==='مستعار'&&l.dueDateISO<today)l.status='متأخر';if(l.status==='متأخر'&&l.dueDateISO>=today)l.status='مستعار'}for(const b of s.books){const active=s.loans.some(l=>l.bookCode===b.code&&['مستعار','متأخر'].includes(l.status));if(active)b.status='مستعار';else if(b.status==='مستعار')b.status='متاح'}return s}
function log(s,type,message,meta={},user='server',stationId=''){s.activityLogs.unshift({id:`LG${Date.now()}${Math.floor(Math.random()*99)}`,type,message,meta,user,stationId:stationId||meta.stationId||'',atISO:new Date().toISOString()});s.activityLogs=s.activityLogs.slice(0,2000)}
function bump(s){s.meta=s.meta||{};s.meta.revision=Number(s.meta.revision||0)+1;s.meta.updatedAt=new Date().toISOString()}
function response(res,status,obj){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(obj))}
async function body(req){let chunks=[],size=0;for await(const c of req){size+=c.length;if(size>5_000_000)throw new Error('payload too large');chunks.push(c)}return chunks.length?JSON.parse(Buffer.concat(chunks).toString('utf8')):{}}
function studentName(s,code){return s.students.find(x=>x.code===code)?.name||code}function bookTitle(s,code){return s.books.find(x=>x.code===code)?.title||code}
async function api(req,res,url){
 if(req.method==='GET'&&url.pathname==='/api/health')return response(res,200,{ok:true,mode:'lan-local',version:'0.4.0'});
 if(req.method==='GET'&&url.pathname==='/api/state'){const s=derive(await readState());return response(res,200,{ok:true,state:s})}
 if(req.method==='PUT'&&url.pathname==='/api/state'){const b=await body(req);return withLock(async()=>{const current=derive(await readState());const currentRev=Number(current?.meta?.revision||0),expected=Number(b.expectedRevision||0);if(current&&expected!==currentRev)return response(res,409,{ok:false,message:'revision conflict',state:current});const next=derive(b.state||{});next.meta=next.meta||{};next.meta.revision=currentRev+1;next.meta.updatedAt=new Date().toISOString();await writeState(next);return response(res,200,{ok:true,state:next})})}
 if(req.method==='POST'&&url.pathname.startsWith('/api/transaction/')){const b=await body(req);return withLock(async()=>{let s=derive(await readState());if(!s)return response(res,409,{ok:false,message:'قاعدة الخادم لم تُهيأ بعد'});const action=url.pathname.split('/').pop();
   if(action==='loan'){
     const st=s.students.find(x=>x.code===b.studentCode),bk=s.books.find(x=>x.code===b.bookCode);if(!st||!bk)return response(res,404,{ok:false,message:'الطالب أو الكتاب غير موجود'});if(st.status!=='نشط')return response(res,409,{ok:false,message:'حساب الطالب موقوف'});if(bk.status!=='متاح')return response(res,409,{ok:false,message:'الكتاب غير متاح حاليًا'});const active=s.loans.filter(l=>l.studentCode===st.code&&['مستعار','متأخر'].includes(l.status));if(active.length>=Number(s.config.maxBooks||3))return response(res,409,{ok:false,message:'بلغ الطالب الحد الأقصى للاستعارة'});if(s.config.preventOverdue&&active.some(l=>l.status==='متأخر'))return response(res,409,{ok:false,message:'لدى الطالب كتاب متأخر'});const q=s.reservations.filter(r=>r.bookCode===bk.code&&r.status==='نشط').sort((a,z)=>(a.createdISO||'').localeCompare(z.createdISO||''));if(q.length&&q[0].studentCode!==st.code)return response(res,409,{ok:false,message:'الكتاب محجوز لطالب آخر'});const due=addDaysISO(Number(s.config.loanDays||14));const loan={id:`LN${Date.now()}`,studentCode:st.code,student:st.name,bookCode:bk.code,book:bk.title,loanDateISO:todayISO(),dueDateISO:due,returnedDateISO:null,status:'مستعار',renewalsUsed:0,stationId:b.stationId||'',createdISO:new Date().toISOString()};s.loans.push(loan);bk.status='مستعار';if(q.length){q[0].status='مكتمل';q[0].fulfilledISO=new Date().toISOString()}log(s,'استعارة',`${st.name} ← ${bk.title}`,{studentCode:st.code,bookCode:bk.code},b.user,b.stationId);bump(s);await writeState(s);return response(res,200,{ok:true,state:s,loan});
   }
   if(action==='return'){
     const l=s.loans.find(x=>x.id===b.loanId&&['مستعار','متأخر'].includes(x.status));if(!l)return response(res,409,{ok:false,message:'الاستعارة غير نشطة'});l.status='تم الإرجاع';l.returnedDateISO=todayISO();const bk=s.books.find(x=>x.code===l.bookCode);if(bk)bk.status='متاح';const q=s.reservations.filter(r=>r.bookCode===l.bookCode&&r.status==='نشط').sort((a,z)=>(a.createdISO||'').localeCompare(z.createdISO||''));if(q.length&&!q[0].expiresISO)q[0].expiresISO=addDaysISO(Number(s.config.reservationDays||3));log(s,'إرجاع',`${l.book} ← ${l.student}`,{studentCode:l.studentCode,bookCode:l.bookCode},b.user,b.stationId);bump(s);await writeState(s);return response(res,200,{ok:true,state:s,loan:l});
   }
   if(action==='renew'){
     const l=s.loans.find(x=>x.id===b.loanId&&['مستعار','متأخر'].includes(x.status));if(!l)return response(res,409,{ok:false,message:'الاستعارة غير نشطة'});if(Number(l.renewalsUsed||0)>=Number(s.config.renewals||0))return response(res,409,{ok:false,message:'تم استنفاد التجديدات'});if(s.reservations.some(r=>r.bookCode===l.bookCode&&r.studentCode!==l.studentCode&&r.status==='نشط'))return response(res,409,{ok:false,message:'يوجد حجز لطالب آخر'});const base=l.dueDateISO>todayISO()?l.dueDateISO:todayISO();l.dueDateISO=addDaysISO(Number(s.config.loanDays||14),base);l.renewalsUsed=Number(l.renewalsUsed||0)+1;l.status='مستعار';log(s,'تجديد',`${l.book} للطالب ${l.student}`,{loanId:l.id},b.user,b.stationId);bump(s);await writeState(s);return response(res,200,{ok:true,state:s,loan:l});
   }
   if(action==='reserve'){
     if(!s.students.some(x=>x.code===b.studentCode)||!s.books.some(x=>x.code===b.bookCode))return response(res,404,{ok:false,message:'الطالب أو الكتاب غير موجود'});if(s.reservations.some(r=>r.studentCode===b.studentCode&&r.bookCode===b.bookCode&&r.status==='نشط'))return response(res,409,{ok:false,message:'يوجد حجز نشط بالفعل'});const r={id:`RS${Date.now()}`,studentCode:b.studentCode,bookCode:b.bookCode,status:'نشط',createdISO:new Date().toISOString(),expiresISO:null};s.reservations.push(r);log(s,'حجز',`${studentName(s,b.studentCode)} حجز ${bookTitle(s,b.bookCode)}`,{studentCode:b.studentCode,bookCode:b.bookCode},b.user,b.stationId);bump(s);await writeState(s);return response(res,200,{ok:true,state:s,reservation:r});
   }
   if(action==='cancel-reservation'){
     const r=s.reservations.find(x=>x.id===b.reservationId&&x.status==='نشط');if(!r)return response(res,404,{ok:false,message:'الحجز غير نشط'});r.status='ملغي';r.cancelledISO=new Date().toISOString();log(s,'إلغاء حجز',`${studentName(s,r.studentCode)} — ${bookTitle(s,r.bookCode)}`,{studentCode:r.studentCode,bookCode:r.bookCode},b.user,b.stationId);bump(s);await writeState(s);return response(res,200,{ok:true,state:s});
   }
   return response(res,404,{ok:false,message:'عملية غير معروفة'});
 })}
 return response(res,404,{ok:false,message:'API not found'});
}
const mime={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon'};
async function staticFile(req,res,url){let rel=decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname);let file=path.normalize(path.join(ROOT,rel));if(!file.startsWith(ROOT)||file.includes(DATA_DIR))return response(res,403,{ok:false});try{const st=await fsp.stat(file);if(st.isDirectory())file=path.join(file,'index.html');const ext=path.extname(file).toLowerCase();res.writeHead(200,{'Content-Type':mime[ext]||'application/octet-stream','Cache-Control':ext==='.html'?'no-store':'public, max-age=60'});fs.createReadStream(file).pipe(res)}catch(e){res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'});res.end('Not found')}}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/'))return await api(req,res,url);return await staticFile(req,res,url)}catch(e){console.error(e);response(res,500,{ok:false,message:'Server error'})}});
server.listen(PORT,'0.0.0.0',()=>{console.log('\nManara Smart Library v0.4 — LAN Server');console.log(`Local: http://localhost:${PORT}`);for(const [name,list] of Object.entries(os.networkInterfaces()))for(const x of list||[])if(x.family==='IPv4'&&!x.internal)console.log(`LAN  : http://${x.address}:${PORT}`);console.log('\nاترك هذه النافذة مفتوحة أثناء تشغيل المحطات.\n')});
